// AUTO-GENERATED by scripts/fetch-news.mjs — do not edit by hand.
// Re-baked on a schedule by .github/workflows/news.yml. Presentation-layer
// flavor ONLY (bar TVs, newspapers): never gate game logic on headlines.
var NEWS_FEED = [
  {
    "t": "Pattaya bakery's 'hairy' croissant stirs pubic reaction",
    "s": "Bangkok Post",
    "d": "06 Jul 2026"
  },
  {
    "t": "Driver tries to beat barrier at Pattaya railway crossing, gets stuck",
    "s": "Thaiger",
    "d": "08 Jul 2026"
  },
  {
    "t": "A Pattaya bakery goes viral for its “pubic hair croissant”(yes, really)",
    "s": "Lifestyle Asia Hong Kong",
    "d": "06 Jul 2026"
  },
  {
    "t": "Jomtien’s rubbish problem refuses to go away",
    "s": "Thaiger",
    "d": "07 Jul 2026"
  },
  {
    "t": "Friend suspects gambling debt link after man found dead on Pattaya beach",
    "s": "Thaiger",
    "d": "07 Jul 2026"
  },
  {
    "t": "2 Chinese surrogacy suspects wanted by China arrested in Pattaya",
    "s": "Thaiger",
    "d": "06 Jul 2026"
  },
  {
    "t": "British tourist loses keycard, threatens Pattaya hotel staff",
    "s": "Thaiger",
    "d": "06 Jul 2026"
  },
  {
    "t": "In Thailand’s sex tourism hub, bright lights flash, loud music blares – and underage girls are exploited",
    "s": "The Guardian",
    "d": "03 Jul 2026"
  },
  {
    "t": "American fitness influencer drowns in Samut Prakan",
    "s": "Bangkok Post",
    "d": "08 Jul 2026"
  },
  {
    "t": "Skeletal remains with 2,000-year-old gold rings found by archaeologists in Thailand",
    "s": "CBS News",
    "d": "07 Jul 2026"
  },
  {
    "t": "Roi Et brings taste of Thailand to Bowling Green",
    "s": "BG Independent News",
    "d": "09 Jul 2026"
  },
  {
    "t": "Loose squirrel causes chaos inside Meta office in Thailand",
    "s": "upi.com",
    "d": "09 Jul 2026"
  },
  {
    "t": "Thailand approves $2bn in investment across nine projects",
    "s": "Yahoo Finance",
    "d": "09 Jul 2026"
  },
  {
    "t": "Fitness influencer Connor Murphy reported dead in Thailand",
    "s": "CBC",
    "d": "09 Jul 2026"
  }
];
// THB per 1 unit — the expat moaning index
var FX_RATES = {"date":"2026-07-09","USD":33.44,"AUD":23.21,"GBP":44.8,"EUR":38.24};
// Pattaya right now — the other moaning index
var WX_NOW = {"date":"2026-07-10","temp":29,"humid":76,"code":0,"hi":32,"rain":12};
// the bar TV's one true channel
var FOOTY = {"league":"World Cup","games":[{"d":"2026-07-06","done":true,"h":"Portugal","hs":0,"a":"Spain","as":1},{"d":"2026-07-07","done":true,"h":"USA","hs":1,"a":"Belgium","as":4},{"d":"2026-07-07","done":true,"h":"Argentina","hs":3,"a":"Egypt","as":2},{"d":"2026-07-07","done":true,"h":"Switzerland","hs":0,"a":"Colombia","as":0},{"d":"2026-07-09","done":false,"h":"France","hs":0,"a":"Morocco","as":0},{"d":"2026-07-10","done":false,"h":"Spain","hs":0,"a":"Belgium","as":0},{"d":"2026-07-11","done":false,"h":"Norway","hs":0,"a":"England","as":0},{"d":"2026-07-12","done":false,"h":"Argentina","hs":0,"a":"Switzerland","as":0}]};
// GLO draw — the girls' retirement plan
var LOTTO = {"date":"2026-07-01","first":"751495","last2":"62","front3":["001","980"],"back3":["304","531"]};
// XAU, plus Thai baht-weight gold (96.5%)
var GOLD = {"usd":4126,"date":"2026-07-09","baht":65250};
// the coin, for the laser-eyed regular
var BTC = {"usd":63158,"thb":2108330};
