// GENERATED by tools/gen-world-export.mjs — do not edit.
// Which portraits have a 384px WebP thumbnail. term.js loads the thumb where
// one exists; everything else keeps its PNG. Regenerate after adding art.
const _THUMBS = new Set(["air","angela","aum","baimon","barry","bebe","belle","benz","bert","bussaba","cake","chaba","chompoo","dave","david","dear","dew","doug","doyle","drew","fahsai","gavin","haad","ing","jenny","joon","joy","jun","kai","kat","kesinee","khing","kluay","kwan","lamai","macca","malai","malila","manow","may","mercedes","mort","nangfah","nee","nina","nook","nu","numfon","pen","pete","peung","phil","pia","powers","poy","praewa","preaw","pukky","puu","rob","roy","saeng","somo","somsak","sopha","superman","tabtim","tan","terry","toi","wayne","wilai"]);
