// Portrait coverage: every character in world.js has a pixel-art bust in
// web/portraits/. When this fails after adding an NPC/patron, add a spec to
// scripts/gen-portraits.py CHARS and re-run it.
import { test } from "node:test";
import assert from "node:assert";
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
for (const f of ["thai.js", "world.js"]) {
  vm.runInThisContext(fs.readFileSync(path.join(root, "web", "js", f), "utf8"), { filename: f });
}
const dir = path.join(root, "web", "portraits");
const PNG_SIG = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

// A character is covered by EITHER a pixel-art PNG here or a WebP thumb — the
// generated masters live in ../portrait_gen, not in web/ (see the size guard
// below), so for a rendered face the thumb IS the shipped art.
test("every NPC and patron has a face", () => {
  const ids = Object.keys(NPCS); // one cast — the patrons are flagged NPCS entries
  const missing = ids.filter(id =>
    !fs.existsSync(path.join(dir, id + ".png")) &&
    !fs.existsSync(path.join(dir, "thumb", id + ".webp")));
  assert.deepEqual(missing, [], "run scripts/gen-portraits.py after adding characters");
});

test("portraits are real PNGs, and none are orphaned", () => {
  const ids = new Set(Object.keys(NPCS)); // one cast
  for (const f of fs.readdirSync(dir)) {
    if (!f.endsWith(".png")) continue;
    const head = fs.readFileSync(path.join(dir, f)).subarray(0, 8);
    assert.ok(head.equals(PNG_SIG), f + " is not a valid PNG");
    assert.ok(ids.has(f.replace(/\.png$/, "")), f + " has no matching character");
  }
});

// The photo-gallery frames (portraits/pics/<stem>.png) are a separate asset set —
// distinct selfie shots referenced by a `pic` on an NPC's paidPics / selfies /
// sponsorPics entry (Wilai's drip, Ping/Lek selfies, the sponsor-cashier loosening
// drip). Generated by portrait_gen's gen_pics.sh, they live in a subfolder the busts'
// coverage/orphan tests skip. Guard them the same way so a mistyped stem fails loud.
const picsDir = path.join(dir, "pics");
function referencedPicStems() {
  const stems = new Set();
  for (const id of Object.keys(NPCS)) {
    const n = NPCS[id];
    for (const pool of [n.paidPics, n.selfies, n.sponsorPics]) {
      if (!Array.isArray(pool)) continue;
      for (const e of pool) if (e && typeof e === "object" && e.pic) stems.add(e.pic);
    }
  }
  return stems;
}

test("every referenced photo-frame stem has a PNG in portraits/pics", () => {
  const missing = [...referencedPicStems()].filter(s => !fs.existsSync(path.join(picsDir, s + ".png")));
  assert.deepEqual(missing, [], "run portrait_gen's gen_pics.sh for these stems");
});

test("portraits/pics frames are real PNGs, and none are orphaned", () => {
  if (!fs.existsSync(picsDir)) return;
  const stems = referencedPicStems();
  for (const f of fs.readdirSync(picsDir)) {
    if (!f.endsWith(".png")) continue;
    const head = fs.readFileSync(path.join(picsDir, f)).subarray(0, 8);
    assert.ok(head.equals(PNG_SIG), "pics/" + f + " is not a valid PNG");
    assert.ok(stems.has(f.replace(/\.png$/, "")), "pics/" + f + " has no referencing entry");
  }
});

// ── The thumbnail track (docs/art-production.md) ───────────────────────────
// portraits/thumb/<id>.webp at 384px is what every small display should load:
// nothing in either game shows a portrait above 140 CSS px, and a full render is
// ~1.44 MB against ~14 KB here. The resolution chain both games share is
//   portraits/thumb/<id>.webp → portraits/<id>.png → drop the element
// so a missing thumb degrades to today's behaviour rather than breaking.
const thumbDir = path.join(dir, "thumb");
const WEBP_SIG = Buffer.from("WEBP", "ascii");
const THUMB_MAX = 60 * 1024;   // real constraint: they land at 14 KB, max 19 KB

// The generated renders — the export's `renders` array is the contract both
// games read, and it's what separates renders from pixel-art placeholders.
function renderIds() {
  const p = path.join(root, "docs", "world-export.json");
  if (!fs.existsSync(p)) return null;
  return JSON.parse(fs.readFileSync(p, "utf8")).renders;
}

test("every generated render has a 384px WebP thumbnail", () => {
  const ids = renderIds();
  if (!ids || !fs.existsSync(thumbDir)) return;  // pre-migration clone
  const missing = ids.filter(id => !fs.existsSync(path.join(thumbDir, id + ".webp")));
  assert.deepEqual(missing, [], "run portrait_gen's gen_thumbs.py");
});

test("thumbnails are real WebP, inside budget, and none are orphaned", () => {
  if (!fs.existsSync(thumbDir)) return;
  const ids = new Set(renderIds() || []);
  for (const f of fs.readdirSync(thumbDir)) {
    if (f.startsWith(".")) continue;
    assert.ok(f.endsWith(".webp"), "thumb/" + f + " is not a .webp");
    const buf = fs.readFileSync(path.join(thumbDir, f));
    assert.ok(buf.subarray(8, 12).equals(WEBP_SIG), "thumb/" + f + " is not a valid WebP");
    const kb = buf.length / 1024;
    assert.ok(buf.length <= THUMB_MAX, `thumb/${f} is ${kb.toFixed(0)} KB — budget is 60 KB`);
    if (ids.size) assert.ok(ids.has(f.replace(/\.webp$/, "")), "thumb/" + f + " matches no render");
  }
});

// The masters do not live here. They are 1.5 MB each, no consumer ever requests
// one (term.js prefers the thumb whenever `_THUMBS` has the id), and `web/` is
// what pages.yml publishes — so 84 of them were shipping with every deploy for
// nothing. They now sit in ../portrait_gen beside the other generation inputs.
// This guard is what stops them drifting back: anything big in web/portraits is
// a master that escaped. (portraits/pics/ is deliberately exempt — those frames
// are displayed full-size in the phone gallery.)
test("no full-size masters in web/portraits", () => {
  const MASTER_MIN = 100 * 1024;
  const strays = fs.readdirSync(dir)
    .filter(f => f.endsWith(".png"))
    .filter(f => fs.statSync(path.join(dir, f)).size > MASTER_MIN);
  assert.deepEqual(strays, [],
    "masters belong in ../portrait_gen — only thumbs and pixel art ship (docs/art-production.md)");
});

test("the generator's cast list matches the world", () => {
  const gen = fs.readFileSync(path.join(root, "scripts", "gen-portraits.py"), "utf8");
  const specIds = [...gen.matchAll(/^    "([a-z_0-9]+)":\s/gm)].map(m => m[1]);
  const world = Object.keys(NPCS).sort(); // one cast — a spread over both would duplicate the bench
  assert.deepEqual(specIds.slice().sort(), world);
});
