// Bake real headlines into web/js/news-data.js (run by the news workflow on
// a cron, or by hand). No dependencies — Google News RSS parsed with regexes.
//
// The output is a classic-script global (var NEWS_FEED = [...]) so the game
// reads it as a plain asset: no runtime fetch, works from file://, and the
// engine stays deterministic — headlines are presentation flavor only.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const OUT = fileURLToPath(new URL("../web/js/news-data.js", import.meta.url));

const FEEDS = [
  ["pattaya", "https://news.google.com/rss/search?q=pattaya&hl=en-US&gl=US&ceid=US:en", 8],
  ["thailand", "https://news.google.com/rss/search?q=thailand&hl=en-US&gl=US&ceid=US:en", 6],
];

const ENT = { amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: " ", "#39": "'", "#039": "'" };
const decode = s => s.replace(/&(#?\w+);/g, (m, e) =>
  ENT[e] || (e[0] === "#" ? String.fromCodePoint(parseInt(e.slice(1), 10) || 63) : m));

// Belt and braces: the file must always be valid, inert JS. Strip anything
// that could read as markup or script, cap the length, collapse whitespace.
const clean = s => decode(s)
  .replace(/<[^>]*>/g, "")
  .replace(/[<>`\\]/g, "")
  .replace(/\s+/g, " ")
  .trim()
  .slice(0, 140);

function parseItems(xml) {
  const out = [];
  for (const m of xml.matchAll(/<item>([\s\S]*?)<\/item>/g)) {
    const it = m[1];
    const rawTitle = (it.match(/<title>(?:<!\[CDATA\[)?([\s\S]*?)(?:\]\]>)?<\/title>/) || [])[1];
    if (!rawTitle) continue;
    const src = clean((it.match(/<source[^>]*>([\s\S]*?)<\/source>/) || [, ""])[1]);
    let title = clean(rawTitle);
    // Google News suffixes " - Source"; drop it when it just repeats the source
    if (src && title.toLowerCase().endsWith(" - " + src.toLowerCase())) {
      title = title.slice(0, -(src.length + 3)).trim();
    }
    const pub = (it.match(/<pubDate>([\s\S]*?)<\/pubDate>/) || [, ""])[1];
    const date = pub ? clean(pub).slice(5, 16) : ""; // "08 Jul 2026"
    if (title.length > 20) out.push({ t: title, s: src, d: date });
  }
  return out;
}

const feed = [];
const seen = new Set();
for (const [tag, url, want] of FEEDS) {
  try {
    const res = await fetch(url, { headers: { "User-Agent": "Mozilla/5.0 (soisanuk news baker)" } });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    let taken = 0;
    for (const item of parseItems(await res.text())) {
      const key = item.t.toLowerCase().slice(0, 60);
      if (seen.has(key)) continue;
      seen.add(key);
      feed.push(item);
      if (++taken >= want) break;
    }
    console.log(`${tag}: ${taken} headlines`);
  } catch (e) {
    console.error(`${tag}: ${e.message}`);
  }
}

if (feed.length < 3) {
  // keep whatever was baked last time rather than shipping an empty paper
  console.error(`only ${feed.length} headlines — keeping the previous bake`);
  process.exit(0);
}

let previous = "";
try { previous = readFileSync(OUT, "utf8"); } catch {}

const body =
  "// AUTO-GENERATED by scripts/fetch-news.mjs — do not edit by hand.\n" +
  "// Re-baked on a schedule by .github/workflows/news.yml. Presentation-layer\n" +
  "// flavor ONLY (bar TVs, newspapers): never gate game logic on headlines.\n" +
  "var NEWS_FEED = " + JSON.stringify(feed, null, 2) + ";\n";

if (body === previous) {
  console.log("headlines unchanged");
} else {
  writeFileSync(OUT, body);
  console.log(`baked ${feed.length} headlines → web/js/news-data.js`);
}
